name: Check website
on:
  push:
    paths:
      - .github/workflows/cronjob.yml
  schedule:
    - cron: "0 */6 * * *"

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: Curl homepage
        run: curl -sSf https://www.petchblog.net/ >/dev/null || { exit 1; }
      - name: Curl article page
        run: curl -sSf https://www.petchblog.net/article/mern-stack >/dev/null || { exit 1; }
      - name: Curl post it app
        run: curl -sSf https://postitapp.petchblog.net/ >/dev/null || { exit 1; }
      - name: Curl top image 1
        run: curl -sSf https://petchblog.s3.ap-southeast-1.amazonaws.com/public/pascal-van-de-vendel-J3pkJFnpDkM-unsplash.jpg >/dev/null || { exit 1; }
      - name: Curl top image 2
        run: curl -sSf https://petchblog.s3.ap-southeast-1.amazonaws.com/public/black-friday-play.png >/dev/null || { exit 1; }
