name: Check website
on:
  push:
  schedule:
    - cron: "0 */23 * * *"

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Curl homepage
        run: curl https://www.petchblog.net/
      - name: Curl article page
        run: curl https://www.petchblog.net/article/mern-stack
      - name: Curl 400 (TEST)
        run: curl -sSf https://www.petchblog.net/some-not-existing-link >/dev/null || { echo "Error: Non-2xx status code received"; exit 1; }
